### ISSUE TITLE
Java api code defect: most (all?) of the inner classes in java_rest_coin_api should be top level

### ISSUE THREAD

**Issue by RobustCoder** [api-bricks/api-bricks-sdk#37]
The Java API essentially has but a single top level class, namely, java_rest_coin_api.

(There is also a top level test class, java_rest_coin_api_test.java, which shows how to use the API.)

That single top level class, however, has tons of inner classes/enums like asset, exchange, etc.

I see no reason why all these inner objects are defined inside the same top level class.  They are fundamental domain objects, therefore, each should be pulled out into its own top level class.

I quickly glanced at the csharp-rest directory in the coinai .zip file, and I see that has proper top level classes for stuff.  Java is no different than C# in regards to how you should nest your classes, so why does the Java API have this unconventional design?

It is an annoying design because you now need to refer to classes with really long unreadable names like "java_rest_coin_api.timedata" when you should just be able to use "timedata".

Also, that java_rest_coin_api class is in the default (unnamed) package, but it should probably be in a named package like "com.coinapi" or something.

**Comment by Svisstack** [comment]
I agree, however, we didn't have the resources to improve design at this moment.

We can discuss some kind of arrangement/benefit if you are willing to refactor this code.

**Comment by RobustCoder** [comment]
Artur,

That's great news.

Greetings from Puerto Rico!  I am here on vacation as of yesterday thru
this coming Sunday.

I am not sure how much work i can get done on this while on vacation, but I
can work on this soon next week.  Will that be OK for you?

I know exactly what steps I will take to address the issues, and I think
that it will take me 5 to 10 hours.  So, I should be able to finish this
project in the next 10 days, even tho I only can do it in my spare time .

Is that schedule OK with you?

Also, do you need me to write you the refactoring steps that I plan on
doing first, or is it OK if I go ahead and do the code changes and then
submit my changed code to you?

I plan on addressing all the issues that I raised on your github site, plus
a few more minor ones.

I am very systematic: I was planning on keeping a journal of all the
changes that I do.

Regards,

Brent Boyer
